fix: fixed tabulation

diff --git a/.github/workflows/deploy-prod.yml b/.github/workflows/deploy-prod.yml
--- a/.github/workflows/deploy-prod.yml
+++ b/.github/workflows/deploy-prod.yml
@@ -21,20 +21,21 @@ jobs:
           echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH
           export PATH="${HOME}/yandex-cloud/bin:$PATH"
           yc --version
-            - name: Check if image exists
-              run: |
-                IMAGE_TAG="${{ github.event.inputs.release_version }}_latest"
-                echo "Checking image: $IMAGE:$IMAGE_TAG"
 
-                TOKEN=$(yc iam create-token)
-                STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
-                  -H "Authorization: Bearer $TOKEN" \
-                  "https://container-registry.api.cloud.yandex.net/v1/repositories/${{ secrets.YC_REGISTRY_ID }}/app/tags/$IMAGE_TAG")
+      - name: Check if image exists
+        run: |
+          IMAGE_TAG="${{ github.event.inputs.release_version }}_latest"
+          echo "Checking image: $IMAGE:$IMAGE_TAG"
 
-                if [ "$STATUS" -ne 200 ]; then
-                  echo "❌ Image with tag $IMAGE_TAG not found in registry"
-                  exit 1
-                fi
+          TOKEN=$(yc iam create-token)
+          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
+            -H "Authorization: Bearer $TOKEN" \
+            "https://container-registry.api.cloud.yandex.net/v1/repositories/${{ secrets.YC_REGISTRY_ID }}/app/tags/$IMAGE_TAG")
+
+          if [ "$STATUS" -ne 200 ]; then
+            echo "❌ Image with tag $IMAGE_TAG not found in registry"
+            exit 1
+          fi
 
       - name: Deploy to Production VM over SSH
         uses: appleboy/ssh-action@v1.0.0
